server:
    port: 8080

spring:
    profiles:
        active: dev
    main:
        allow-circular-references: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
minio:
    url: http://127.0.0.1:9000
    username: minioadmin
    password: minioadmin
    bucketName: avatars

